FROM mcr.microsoft.com/dotnet/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_URLS=http://+
ENV ASPNETCORE_ENVIRONMENT=Development
ENV SampleTasks_Serilog__SeqServerUrl=http://host.docker.internal:5100/
ENV SampleTasks_EventBusConnection=host.docker.internal
ENV SampleTasks_CheckUpdateTime=30000
#ENV SampleTasks_RabbitMQ__UserName=${SAMPLE_SERVICE_BUS_USERNAME}
#ENV SampleTasks_RabbitMQ__Password=${SAMPLE_SERVICE_BUS_PASSWORD}
EXPOSE 80

COPY BuildingBlocks/EventBus/EventBus/EventBus.csproj src/BuildingBlocks/EventBus/EventBus/
COPY BuildingBlocks/EventBus/EventBus.Tests/EventBus.Tests.csproj src/BuildingBlocks/EventBus/EventBus.Tests/
COPY BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj src/BuildingBlocks/EventBus/EventBusRabbitMQ/
COPY BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj src/BuildingBlocks/EventBus/EventBusServiceBus/
COPY BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj src/BuildingBlocks/EventBus/IntegrationEventLogEF/
COPY BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj src/BuildingBlocks/WebHostCustomization/WebHost.Customization/
COPY SampleEB/SampleEB.API/SampleEB.API.csproj src/SampleEB/SampleEB.API/
COPY SampleEB/SampleEB.Domain/SampleEB.Domain.csproj src/SampleEB/SampleEB.Domain/
COPY SampleEB/SampleEB.Persistence/SampleEB.Persistence.csproj src/SampleEB/SampleEB.Persistence/
COPY SampleEB/SampleEB.Tasks/SampleEB.Tasks.csproj src/SampleEB/SampleEB.Tasks/

RUN dotnet restore src/SampleEB/SampleEB.Tasks

COPY BuildingBlocks/ src/BuildingBlocks/
COPY SampleEB/SampleEB.Tasks src/SampleEB/SampleEB.Tasks

WORKDIR /src/SampleEB/SampleEB.Tasks/
RUN dotnet build --no-restore -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "--"]